name: weather_repository
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  open_meteo_api:
    path: ../open_meteo_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail: ^1.0.3
  test: ^1.24.9

flutter: